### ISSUE TITLE
Observer not working when change orientation

### ISSUE THREAD

**Issue by SarahSami** [SubhrajyotiSen/Borrow#1]
I changed orientation then added new Borrowed item but RecyclerView not updated

**Comment by SubhrajyotiSen** [comment]
Thanks for the report. I am working on it.

**Comment by SubhrajyotiSen** [comment]
Hey! I have pushed a commit to fix the issue for now. It's not the ideal fix but I am working on a cleaner fix.

**Comment by SubhrajyotiSen** [comment]
So I spoke to someone at Google and turns out there is no need to explicitly destroy the Instance. So the bug can be marked resolved.
